name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main
  #Task 1:
  #add a manual workflow trigger
  workflow_dispatch:

  check_run:
    types: [rerequested, completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


     	#Task 2:
        #Add a step to run the unit test
    - name: run unit test
      run: |
        python -m unittest discover -s tests

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
	#Task 3:
        #i: create a service account and export it's json key
        #ii: create a github action scret call GAE_SA_KEY, 
	#and use the json key above as the content
        credentials_json: ${{ secrets.GAE_SA_KEY }}

    - name: Deploy to App Engine
      run: |
	#Task 4:
	#There is just one more thing to do
        gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --quiet
